# Generated by Django 3.2.5 on 2021-07-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion de la empresa')),
                ('nit', models.CharField(max_length=255, verbose_name='Nit de la empresa')),
                ('telefono', models.CharField(max_length=255, verbose_name='Telefono de la empresa')),
            ],
        ),
    ]
