# Generated by Django 3.2.5 on 2021-07-31 18:34

from django.db import migrations

def create_data(apps, schema_editor):
    Customer = apps.get_model('empresas', 'Empresa')
    Customer(nombreEmpresa="Empresa Prueba", direccion="direccion prueba", nit="1234567", telefono="00000000").save()

class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
